<h1>Ordinal Encoding</h1>

<h2>Setup</h2>

In [13]:
# Standard libraries
import numpy as np
import pandas as pd
import seaborn as sns

# Preprocessing libraries
from sklearn.preprocessing import OrdinalEncoder

<h2>Diamond Exemple</h2>

In [9]:
# Data path 
Diamonds_data_path = "/Users/johanndurand-vegas/GIT/AI-Practical_ML-PRO/01_Pilier_de_lIA/Methodologie_IA/4_Preprocessing/data/diamonds.csv"

In [10]:
# Load the diamond dataset into a DataFrame
#df = sns.load_dataset("diamonds") # ERROR : certificate pb
df = pd.read_csv(Diamonds_data_path)

# Display the table
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


<h3>1. <u>Encodage brutale</u></h3>

In [14]:
# Instantiate an encoder object from the OrdinalEncoder class
encoder = OrdinalEncoder()

# Adjust the encoder to our data : the three columns
encoder.fit(df[["cut", "color", "clarity"]])

# Transform the categories of each column into numerical values
encoder.transform(df[["cut", "color", "clarity"]])

array([[2., 1., 3.],
       [3., 1., 2.],
       [1., 1., 4.],
       ...,
       [4., 0., 2.],
       [3., 4., 3.],
       [2., 0., 3.]])

<h3>2. <u>Définir l'ordre de l'encodage</u></h3>

In [17]:
for col in ['cut', 'color', 'clarity']:
    print(f"{col} : {df[col].unique()}")

cut : ['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
color : ['E' 'I' 'J' 'H' 'F' 'G' 'D']
clarity : ['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']


In [23]:
# Order to respect 
cut_order = ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']
color_order = ['J', 'I', 'H', 'G', 'F', 'E', 'D']
clarity_order = ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']

In [24]:
# Instantiate an encoder object from the OrdinalEncoder class
encoder = OrdinalEncoder(categories=[cut_order, color_order, clarity_order])

# Adjust the encoder to our data : the three columns
encoder.fit(df[["cut", "color", "clarity"]])

# Transform the categories of each column into numerical values
encoder.transform(df[["cut", "color", "clarity"]])

array([[4., 5., 1.],
       [3., 5., 2.],
       [1., 5., 4.],
       ...,
       [2., 6., 2.],
       [3., 2., 1.],
       [4., 6., 1.]])

<h3>3. <u>Cas de nouvelles catégories</u></h3>

In [29]:
# Instantiate an encoder object from the OrdinalEncoder class
encoder = OrdinalEncoder(
			categories=[cut_order, color_order, clarity_order]
			, handle_unknown = 'use_encoded_value'
			, unknown_value = -1
		)

# Adjust the encoder to our data : the three columns
encoder.fit(df[["cut", "color", "clarity"]])

# Transform the categories of each column into numerical values
encoder.transform(df[["cut", "color", "clarity"]])

array([[4., 5., 1.],
       [3., 5., 2.],
       [1., 5., 4.],
       ...,
       [2., 6., 2.],
       [3., 2., 1.],
       [4., 6., 1.]])

In [31]:
# Try with a new value
encoder.transform([["Fair", "G", "A+"]])

/Users/johanndurand-vegas/GIT/AI-Practical_ML-PRO/01_Pilier_de_lIA/Methodologie_IA/.venv/lib/python3.9/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[ 0.,  3., -1.]])